defmodule Secrets do

  def options do
    [
      'the shawshank redemption',
      'the godfather',
      'pulp fiction',
      'the dark knight',
      'fight club',
      'goodfellas',
      'inception',
      'seven samurai',
      'forrest gump',
      'the matrix',
      'city of god',
      'once upon a time in the west',
      'the silence of the lambs',
      'the usual suspects',
      'casablanca',
      'raiders of the lost ark',
      'rear window',
      'psycho',
      'american history x',
      'saving private ryan',
      'memento',
      'apocalypse now',
      'city lights',
      'spirited away',
      'alien',
      'modern times',
      'life is beautiful',
      'back to the future',
      'the pianist',
      'north by northwest',
      'the shining',
      'citizen kane',
      'the departed',
      'paths of glory',
      'the intouchables',
      'the green mile',
      'gladiator',
      'american beauty',
      'the dark knight rises',
      'django unchained',
      'vertigo',
      'aliens',
      'gravity',
      'double indemnity',
      'the lives of others',
      'taxi driver',
      'the great dictator',
      'the prestige',
      'a clockwork orange',
      'lawrence of arabia',
      'to kill a mockingbird',
      'reservoir dogs',
      'cinema paradiso',
      'das boot',
      'the lion king',
      'the treasure of the sierra madre',
      'requiem for a dream',
      'once upon a time in america',
      'braveheart',
      'eternal sunshine of the spotless mind',
      'the third man',
      'full metal jacket',
      'princess mononoke',
      'metropolis',
      'bicycle thieves',
      'rashomon',
      'all about eve',
      'witness for the prosecution',
      'some like it hot',
      'amadeus',
      'grave of the fireflies',
      'chinatown',
      'the sting',
      'monty python and the holy grail',
      'the apartment',
      'unforgiven',
      'indiana jones and the last crusade',
      'raging bull',
      'die hard',
      'yojimbo',
      'the bridge on the river kwai',
      'batman begins',
      'for a few dollars more',
      'inglourious basterds',
      'toy story',
      'pans labyrint',
      'on the waterfront',
      'the great escape',
      'downfall',
      'the kid',
      'att leva',
      'heat',
      'the general',
      'the seventh seal',
      'scarface',
      'the elephant man',
      'blade runner',
      'wild strawberries',
      'the maltese falcon',
      'rebecca',
      'gran torino',
      'fargo',
      'the big lebowski',
      'the gold rush',
      'the hunt',
      'it happened one night',
      'cool hand luke',
      'the deer hunter',
      'touch of evil',
      'diabolique',
      'good will hunting',
      'judgment at nuremberg',
      'the sixth sense',
      'casino',
      'no country for old men',
      'butch cassidy and the sundance kid',
      'gone with the wind',
      'trainspotting',
      'platoon',
      'sin city',
      'the thing',
      'jaws',
      'the wizard of oz',
      'my neighbor totoro',
      'the grapes of wrath',
      'the secret in their eyes',
      'hotel rwanda',
      'strangers on a train',
      'annie hall',
      'warrior',
      'v for vendetta',
      'finding nemo',
      'high noon',
      'dial m for murder',
      'into the wild',
      'how to train your dragon',
      'rush',
      'life of brian',
      'the best years of our lives',
      'the avengers',
      'notorious',
      'network',
      'million dollar baby',
      'there will be blood',
      'stand by me',
      'terminator',
      'twelve monkeys',
      'amores perros',
      'groundhog day',
      'the night of the hunter',
      'the big sleep',
      'a beautiful mind',
      'donnie darko',
      'gandhi',
      'dog day afternoon',
      'the bourne ultimatum',
      'persona',
      'the graduate',
      'the killing',
      'the princess bride',
      'the hustler',
      'black swan',
      'fanny and alexander',
      'i faderns namn',
      'rocky',
      'before midnight',
      'la strada',
      'the man who shot liberty valance',
      'the exorcist',
      'anatomy of a murder',
      'slumdog millionaire',
      'infernal affairs',
      'the manchurian candidate',
      'barry lyndon',
      'rope',
      'roman holiday',
      'the truman show',
      'memories of murder',
      'life of pi',
      'nawals hemlighet',
      'the wild bunch',
      'jurassic park',
      'rang de basanti',
      'all quiet on the western front',
      'prisoners',
      'the diving bell and the butterfly',
      'ip man',
      'sleuth',
      'shutter island',
      'star trek',
      'like stars on earth',
      'stalker',
      'a streetcar named desire',
      'la haine',
      'ratatouille',
      'rain man',
      'before sunrise',
      'the celebration',
      'in the mood for love',
      'bringing up baby',
      'castle in the sky'
    ]
  end
end

